# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac7cfded3548f7ea3d08cf7705ca0d644cc9009c8934dffc880ae4f4b48f9c53be33dcbcc631f393e8a573de983a85cdf042ce8b22721fa88dbbb5d7bb94fba9

test:
  secret_key_base: c40fcedec86024f57abda9db7880d670662fd5212944693890675d01ddb970d6b0b5bef21ece44a8f2dcd3a07e0a4b5ae762b94c9e910649100641849697421e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
